# Generated by Django 5.1 on 2024-09-05 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('surname', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=120, null=True)),
                ('course_format', models.CharField(blank=True, max_length=120, null=True)),
                ('course_type', models.CharField(blank=True, max_length=120, null=True)),
                ('sum', models.IntegerField(blank=True, null=True)),
                ('alreadyPaid', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utm', models.CharField(blank=True, max_length=120, null=True)),
                ('msg', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('admin_panel', 'Admin'), ('manager', 'Manager')], default='manager', max_length=10)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
