# Generated by Django 5.0.7 on 2024-07-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
