# Generated by Django 5.1 on 2024-09-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_group_ordermodel_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
